app:
  # 是否启用ansi控制台输出有颜色的字体
  enable-ansi: true
  token:
    expiry: 7
server:
  port: 9090
  servlet:
    context-path: /
spring:
  resources:
    static-locations: classpath:/WEB-INF/static/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/material?useUnicode=true&serverTimezone=CTT&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: 123456
    #hikari 连接最大生命时长
    hikari:
      max-lifetime: 30000
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
aliyun:
  sms:
    accessKeyId: LTAI4FyqCyc884owHNTvgfeK
    accessKeySecret: Qmaq7ZMfeOnx7OLUx2gcfqmXYaLOCy
  oss:
    accessKeyId: LTAI4GA549m89fqu5n5aRBP6
    accessKeySecret: d4FyQEjKyqjxvfkZke0VcV0fAchDOi
    endpoint: oss-cn-shenzhen.aliyuncs.com
    bucket: w1chat
sms:
  code:
    #是否真实发送短信验证码
    realSend: false